language: php

php:
  - 5.6
  - 7

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml
  - wget -O codecov.sh https://codecov.io/bash
  - bash codecov.sh
after_script:
  - php vendor/bin/codacycoverage clover clover.xml --verbose
notifications:
  email: false