language: php

php:
  - 5.6
  - 7

env:
  global:
    - DEFAULT=1
    - CODECOV_TOKEN=f92e54c5-e70c-45ad-9f7d-0a4eb9414bdb

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: CODECOVERAGE=1 DEFAULT=0

before_script:
  - sh -c "if [ '$CODECOVERAGE' != '1' ]; then phpenv config-rm xdebug.ini; fi"

  - sudo apt-get install wkhtmltopdf -y
  - sudo touch /usr/bin/latexpdf && sudo chmod +x /usr/bin/latexpdf

  - composer self-update
  - composer require dompdf/dompdf --no-update
  - composer install --no-interaction

  - sh -c "if [ '$PHPCS' = '1' ]; then composer require cakephp/cakephp-codesniffer:dev-master; fi"

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit; fi"

  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config; fi"

  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then wget -O codecov.sh https://codecov.io/bash; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then bash codecov.sh; fi"
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false