language: php

php:
  - 5.6
  - 7

before_script:
  - composer install --no-interaction

script:
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then wget -O codecov.sh https://codecov.io/bash; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then bash codecov.sh; fi"
after_script:
  - php vendor/bin/codacycoverage clover clover.xml --verbose
notifications:
  email: false